name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3     
      - run: docker build -t arjunkhadka5docker/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true arjunkhadka5docker/react-test npm test

      - run: docker build -t arjunkhadka5docker/multi-client ./client
      - run: docker build -t arjunkhadka5docker/multi-nginx ./nginx
      - run: docker build -t arjunkhadka5docker/multi-server ./server
      - run: docker build -t arjunkhadka5docker/multi-worker ./worker
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push arjunkhadka5docker/multi-client
      - run: docker push arjunkhadka5docker/multi-nginx
      - run: docker push arjunkhadka5docker/multi-server
      - run: docker push arjunkhadka5docker/multi-worker

      - name: Generate deployment package
        run: zip -r deploy.zip docker-compose.yml

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          application_name: multi-docker
          environment_name: Multi-docker-env
          version_label: ${{ github.sha }}
          region: us-east-2
          existing_bucket_name: elasticbeanstalk-us-east-2-399404565736
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          deployment_package: deploy.zip
          
