name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3     
      - run: docker build -t arjunkhadka/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true rallycoding/react-test npm test

      - run: docker build -t arjunkhadka/multi-client ./client
      - run: docker build -t arjunkhadka/multi-nginx ./nginx
      - run: docker build -t arjunkhadka/multi-server ./server
      - run: docker build -t arjunkhadka/multi-worker ./worker
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push arjunkhadka/multi-client
      - run: docker push arjunkhadka/multi-nginx
      - run: docker push arjunkhadka/multi-server
      - run: docker push arjunkhadka/multi-worker
